public class PlaylistCreator {
  public static Music[] createPlaylist() {
    return new Music[] {
        new Music("Square Hammer", "Ghost", 2016),
        new Music("Lithium", "Nirvana", 1991),
        new Music("Rain On Me", "Lady Gaga", 2020),
        new Music("Wind of Chnge", "Scorpions", 1990),
        new Music("Always Somewhere", "Scorpions", 1979),
        new Music("Girls, Girls, Girls", "Mötley Crüe", 1987),
        new Music("Still Loving You", "Scorpions", 2011),
        new Music("Rock ANd Roll All Nite", "KISS", 1975),
        new Music("Darkness At The Heart Of My Love", "Ghost", 2022),
        new Music("Thunder", "Imagine Dragons", 2017),
        new Music("Spillways", "Ghost", 2023),
        new Music("Centuries", "Fall Out Boy", 2015),
        new Music("God Of Thunder", "KISS", 1976),
        new Music("Boulevard Of Broken Dreams", "Green Day", 2004),
        new Music("Otherside", "Red Hot Chilli Peppers", 1999),
        new Music("Rats", "Ghost", 2018),
        new Music("Sweater Weather", "The Neighbourhood", 2013),
        new Music("All The Small Things", "blink-182", 2005),
        new Music("Zenith", "Ghost", 2023),
        new Music("Chop Suey!", "System Of A Down", 2001),
        new Music("It's My Life", "Bon Jovi", 2000),
        new Music("Mary On A Cross", "Ghost", 2019),
        new Music("No More Tears", "Ozzy Osbourne", 1991),
        new Music("Call Me Little Sunshine", "Ghost", 2022),
        new Music("Mummy Dust", "Ghost", 2016),
        new Music("Send Me An Angel", "Scorpions", 1990),
        new Music("Natural", "Imagine Dragons", 2018),
        new Music("War Machine", "KISS", 1982),
        new Music("Kiss The Go-Goat", "Ghost", 2019),
        new Music("November Rain", "Guns N' Roses", 1991),
        new Music("Whatever It Takes", "Imagine Dragons", 2017),
        new Music("Coming Undone", "Korn", 2005),
        new Music("No Surrender", "Judas Priest", 2018),
        new Music("Year Zero", "Ghost", 2013),
        new Music("Dani California", "Red Hot Chilli Peppers", 2006),
        new Music("Per Aspera Ad Inferi", "Ghost", 2013),
        new Music("Detroit Rock City", "KISS", 1988),
        new Music("Watcher In The Sky", "Ghost", 2022),
        new Music("Holliday", "Green Day", 2004),
        new Music("Heaven's On Fire", "KISS", 1984),
        new Music("With Or Without You", "U2", 1987),
        new Music("Diggy Diggy Hole", "Wind Rose", 2019),
        new Music("From The Pinnacle To The Pit", "Ghost", 2016),
        new Music("Strutter", "KISS", 1974),
        new Music("You Give Love A Bad Name", "Bon Jovi", 1986),
        new Music("I Was Made For Loving You", "KISS", 1979),
        new Music("Smoke On The Water", "Deep Purple", 1972),
        new Music("Summer Of Love", "U2", 2017),
        new Music("When You Came Into My Life", "Scorpions", 2017),
        new Music("Rock You Like A Hurricane", "Scorpions", 1984),
        new Music("Witch Image", "Ghost", 2018),
    };
  }
}
